language: objective-c
osx_image: xcode7

notifications:
  email: false

env:
  - GAME_NAME=MyGame
  - COMPANY_NAME=MyCompany

script: 
  - xctool -project $COMPANY_NAME/$GAME_NAME/proj.ios_mac/$GAME_NAME.xcodeproj -scheme $GAME_NAME-mobile build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
